**Trabajo con Pandas**

***15.11.2017***

In [5]:
import pandas as pd

****Para que jupyter me muestre graficos****

In [6]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [7]:
train = pd.read_csv('/home/ubuntu/MachineLearningTest/data/train.csv')

In [8]:
train.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    2  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

In [ ]:
train.head(22)

In [ ]:
train.describe()

In [ ]:
train.age

In [ ]:
train.num

In [ ]:
train.age.plot()

In [ ]:
train['age'].hist()

In [ ]:
train.age.hist()

In [ ]:
train.hist(figsize=(20,20))

In [ ]:
train.hist()

In [ ]:
train.boxplot('age')

In [ ]:
train.boxplot('num')

In [ ]:
train.plot()

*** Localizar un valor concreto. Fil 22 Col 3 ***  
iloc[fila,columna] Tener en cuenta que comenzamos a numerar por el 0

In [ ]:
train.iloc[21,2]

***Así saco la edad del registro 22***

In [ ]:
train.loc[21,'age']

***Tamaño de la tabla***  
Devuelve filas y columnas en una tupla

In [9]:
train.shape

(264, 14)

##### *** Sólo quiero las filas***

In [10]:
nrow = train.shape[0]

***Igual mediante lenght ***

In [15]:
nrow == len(train['num'])

True

In [17]:
nrow == len(train.age)

True

In [11]:
nrow

264

In [12]:
train.num

0      0
1      2
2      1
3      0
4      0
5      0
6      3
7      0
8      2
9      1
10     0
11     0
12     2
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     3
24     4
25     0
26     0
27     0
28     0
29     3
      ..
234    0
235    3
236    2
237    1
238    0
239    0
240    0
241    0
242    0
243    2
244    0
245    2
246    2
247    1
248    3
249    0
250    0
251    1
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    3
262    0
263    0
Name: num, Length: 264, dtype: int64

***Valores distintos***

In [20]:
train.num.unique()

array([0, 2, 1, 3, 4])

In [21]:
train.num.unique

<bound method Series.unique of 0      0
1      2
2      1
3      0
4      0
5      0
6      3
7      0
8      2
9      1
10     0
11     0
12     2
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     3
24     4
25     0
26     0
27     0
28     0
29     3
      ..
234    0
235    3
236    2
237    1
238    0
239    0
240    0
241    0
242    0
243    2
244    0
245    2
246    2
247    1
248    3
249    0
250    0
251    1
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    3
262    0
263    0
Name: num, Length: 264, dtype: int64>

In [ ]:
for elemento in train.num:
    print(elemento)

***Así modifico un valor***

In [ ]:
for i in range(nrow):
    print(i)

#loc referencia a index y columna / iloc referencia numericamente

In [ ]:
for i in range(nrow):
    if train['num'][i] == 0:
        print(train['num'][i])

In [13]:
for i in range(nrow):
    if train['num'][i] != 0:
        train.loc[i,'num'] = 1

In [14]:
train.num.unique()

array([0, 1])

** num ** es la variable que me dice si una persona está enferma o no. 0 es sano y el resto enferma. Es la variable con la que vamos a trabajar

*** Preprocessing ***  
Vamos a asignar el valor media a aquellas variables que contienen NaN

In [15]:
from sklearn.preprocessing import Imputer

Axis 0 es para columnas y 1 para filas. La siguiente consulta me devuelve todos los registros y con False me dice que ese valor no es nulo.

In [16]:
train.shape

(264, 14)

In [26]:
train.isnull()

age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0    False  False  False     False  False  False    False    False  False   
1    False  False  False     False  False  False    False    False  False   
2    False  False  False     False  False  False    False    False  False   
3    False  False  False     False  False  False    False    False  False   
4    False  False  False     False  False  False    False    False  False   
5    False  False  False     False  False  False    False    False  False   
6    False  False  False     False  False  False    False    False  False   
7    False  False  False     False  False  False    False    False  False   
8    False  False  False     False  False  False    False    False  False   
9    False  False  False     False  False  False    False    False  False   
10   False  False  False     False  False  False    False    False  False   
11   False  False  False     False  False  False    False    False  False   
12   False  False  False     False  False  False    False    False  False   
13   False  False  False     False  False  False    False    False  False   
14   False  False  False     False  False  False    False    False  False   
15   False  False  False     False  False  False    False    False  False   
16   False  False  False     False  False  False    False    False  False   
17   False  False  False     False  False  False    False    False  False   
18   False  False  False     False  False  False    False    False  False   
19   False  False  False     False  False  False    False    False  False   
20   False  False  False     False  False  False    False    False  False   
21   False  False  False     False  False  False    False    False  False   
22   False  False  False     False  False  False    False    False  False   
23   False  False  False     False  False  False    False    False  False   
24   False  False  False     False  False  False    False    False  False   
25   False  False  False     False  False  False    False    False  False   
26   False  False  False     False  False  False    False    False  False   
27   False  False  False     False  False  False    False    False  False   
28   False  False  False     False  False  False    False    False  False   
29   False  False  False     False  False  False    False    False  False   
..     ...    ...    ...       ...    ...    ...      ...      ...    ...   
234  False  False  False     False  False  False    False    False  False   
235  False  False  False     False  False  False    False    False  False   
236  False  False  False     False  False  False    False    False  False   
237  False  False  False     False  False  False    False    False  False   
238  False  False  False     False  False  False    False    False  False   
239  False  False  False     False  False  False    False    False  False   
240  False  False  False     False  False  False    False    False  False   
241  False  False  False     False  False  False    False    False  False   
242  False  False  False     False  False  False    False    False  False   
243  False  False  False     False  False  False    False    False  False   
244  False  False  False     False  False  False    False    False  False   
245  False  False  False     False  False  False    False    False  False   
246  False  False  False     False  False  False    False    False  False   
247  False  False  False     False  False  False    False    False  False   
248  False  False  False     False  False  False    False    False  False   
249  False  False  False     False  False  False    False    False  False   
250  False  False  False     False  False  False    False    False  False   
251  False  False  False     False  False  False    False    False  False   
252  False  False  False     False  False  False    False    False  False   
253  False  False  False     False  False  False    False    False  False   
254

axis 0 Para que lo haga por columnas

Esta siguiente consulta me dice las columnas en las que hay nulos

In [ ]:
train.isnull().any()

Así obtengo la fila con nulos

In [ ]:
train.isnull().any(1)

Y así me quedo con aquellas filas que contienen los nulos

In [17]:
train.loc[train.isnull().any(1)]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
87   53.0  0.0  3.0     128.0  216.0  0.0      2.0    115.0    0.0      0.0   
166  52.0  1.0  3.0     138.0  223.0  0.0      0.0    169.0    0.0      0.0   
192  43.0  1.0  4.0     132.0  247.0  1.0      2.0    143.0    1.0      0.1   

     slope   ca  thal  num  
87     1.0  0.0   NaN    0  
166    1.0  NaN   3.0    0  
192    2.0  NaN   7.0    1

Aquí le digo que la transformación que quiero hacer es calcular la media y asignarla a los valores nulos. En lugar de transformar también podría decirle que lo que quiero es predecir

Y ahora aplico esa transformación

In [18]:
train.shape

(264, 14)

In [19]:
#train = pd.DataFrame(imp.transform(train),columns=train.columns).loc[train.isnull().any(1)]
train = train.fillna(train.mean())

In [20]:
train.shape

(264, 14)

In [21]:
train.loc[train.isnull().any(1)]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, num]
Index: []

In [ ]:
train.groupby("sex").sum()

In [ ]:
train.groupby('sex').size()

In [ ]:
train.plot(kind='scatter', x='num', y='age')

*** Url de referencia para pintar el scatter_matrix ***

In [ ]:
from pandas.plotting import scatter_matrix

In [ ]:
scatter_matrix(train, alpha=0.2, figsize=(80,80), diagonal='kde')

*** Cargamos el dataset que vamos a utilizar como datos de test ***

*** Vamos a dividir en dos nuestro dataset de train. Una parte para el training y otra para la validación. No vamos a utilizar el dataset test.  
Primero nos quedamos con todas las filas y todas las columnas menos num, que es la columna a predecir, y lo asignamos a la variable X***

In [32]:
train.iloc[:,:-1].as_matrix()

array([[ 63.,   1.,   1., ...,   3.,   0.,   6.],
       [ 67.,   1.,   4., ...,   2.,   3.,   3.],
       [ 67.,   1.,   4., ...,   2.,   2.,   7.],
       ..., 
       [ 58.,   0.,   2., ...,   1.,   2.,   3.],
       [ 60.,   0.,   1., ...,   1.,   0.,   3.],
       [ 44.,   1.,   3., ...,   1.,   0.,   3.]])

***Ahora extraemos la variable num y esa columna la asignamos a la variable y***

In [33]:
train.iloc[:,-1].as_matrix()

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

***Aquí es donde hacemos la asignación a X y a y***

In [22]:
X, y = train.iloc[:,:-1].as_matrix(), train.iloc[:,-1].as_matrix()

In [23]:
train.shape

(264, 14)

In [36]:
X.shape

(264, 13)

In [37]:
y.shape

(264,)

In [39]:
print(X.ndim)

2


In [38]:
print(y.ndim)

1


In [27]:
X

array([[ 63.,   1.,   1., ...,   3.,   0.,   6.],
       [ 67.,   1.,   4., ...,   2.,   3.,   3.],
       [ 67.,   1.,   4., ...,   2.,   2.,   7.],
       ..., 
       [ 58.,   0.,   2., ...,   1.,   2.,   3.],
       [ 60.,   0.,   1., ...,   1.,   0.,   3.],
       [ 44.,   1.,   3., ...,   1.,   0.,   3.]])

In [28]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

*** Ahora dividimos X y y en dos partes. Una para train y otra para test (para corroborar cómo ha ido nuestra predicción.  
Mediante test_size le indico que tome el 66% de los datos para hacer el train y deje el 33% restante para hacer el test. Cada vez que lo ejecute dividirá ese dataset en esas proporciones, pero tomará unos datos distintos cada vez.***

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
X_test

array([[ 59.,   1.,   4., ...,   3.,   0.,   7.],
       [ 68.,   0.,   3., ...,   2.,   0.,   3.],
       [ 39.,   1.,   3., ...,   1.,   0.,   3.],
       ..., 
       [ 54.,   1.,   4., ...,   2.,   1.,   7.],
       [ 70.,   1.,   4., ...,   3.,   0.,   7.],
       [ 29.,   1.,   2., ...,   1.,   0.,   3.]])

***Contra estos valores de y_test vamos a comparar nuestras predicciones utilizando Random Forest***

In [27]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

***Vamos ahora con nuestro RandomForest***

In [28]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0)

In [46]:
clf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

***Entrenamos nuestro algoritmo utilizando X_train y validando contra X_test. Cuando haya terminado el entrenamiento, utilizamos y_train para predecir y_pred***

In [29]:
y_pred = clf.fit(X_train, y_train).predict(X_test)

In [30]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [31]:
from sklearn.metrics import confusion_matrix

***Visualizamos la matriz de confusión, que es la que compara los resultados del algoritmo 'y_pred' contra los valores reales 'y_test'. De esta forma, sabemos el grado de acierto de nuestro algoritmo***

In [32]:
cnf_matrix = confusion_matrix(y_test, y_pred)

In [33]:
cnf_matrix

array([[41,  3],
       [10, 34]])

In [34]:
pd.DataFrame(cnf_matrix,columns=['no','si'], index=['no','si'])

no  si
no  41   3
si  10  34

***10 son los no enfermos que el modelo ha dicho que sí lo están y 3 son enfermos que mi modelo dijo que no lo eran.  
Dependiendo de la naturaleza de los datos con los que estemos trabajando nos puede interesar predecir más enfermos, para prevenir y hacerles un reconocimiento antes de que enfermen. En otros casos puede ser que nos interese lo contrario.***

*** Ahora vamos a escribir una función que nos permita lanzar el modelo varias veces (5 por ejemplo). Vamos a guardar los datos de entrada y las matrices de confusión de cada uno de ellos ***

In [35]:
nsplit = 5
perc = 0.33

def traintest(nsplit, perc):
    results = []
    for i in range(nsplit):
        results_int = []
        
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=perc)
        clf = RandomForestClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0)
        y_pred = clf.fit(X_train, y_train).predict(X_test)
        cnf_matrix = confusion_matrix(y_test, y_pred)
        
        results_int.append('------Item------')
        #results_int.append(X_train)
        #results_int.append(X_test)
        #results_int.append(y_train)
        #results_int.append(y_test)
        #results_int.append(y_pred)
        results_int.append(cnf_matrix)
        results.append(results_int)
    return results

traintest(nsplit, perc)

#Si añado: random_state=42 al train_test_split me salen siempre los mismos valores

[['------Item------', array([[37,  4],
         [19, 28]])], ['------Item------', array([[38,  8],
         [ 8, 34]])], ['------Item------', array([[45,  8],
         [12, 23]])], ['------Item------', array([[40,  2],
         [18, 28]])], ['------Item------', array([[42,  7],
         [10, 29]])]]

*** Ahora vamos a utilizar Análisis de Componentes principales (PCA) para reducir nuestras variables de entrada y que automáticamente se quede con las más significativas.***

In [36]:
from sklearn.decomposition import PCA

**** Si queremos podemos dejar vacío el número de componentes principales para que sea el algoritmo el que lo ajuste ****

In [163]:
pca = PCA(11)

In [164]:
Xtr =pca.fit(X).transform(X)

In [165]:
X_train, X_test, y_train, y_test = train_test_split(Xtr, y, test_size=0.33)

In [166]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0)

In [167]:
y_pred = clf.fit(X_train, y_train).predict(X_test)

In [168]:
cnf_matrix = confusion_matrix(y_test, y_pred)

In [169]:
pd.DataFrame(cnf_matrix,columns=['no','si'], index=['no','si'])

no  si
no  39   9
si  11  29

*** Parece que hay demasiada variación en los resultados aún ejecutando varias veces con el mismo número de componentes principales ***