## EMPEZANDO CON PANDAS

### Importación de librería

In [2]:
import pandas as pd
import numpy as np

### Cargando datos del archivo maestro

In [3]:
train = pd.read_csv('C:\\Users\\Usuario\\Desktop\\MachineLearningTest-master\\data\\train.csv')

### Cabecera de los datos

In [4]:
train.head(6)

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
5  56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    2  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0  
5    1.0  0.0   3.0    0

### Eliminación de los NaN

In [15]:
train = train.fillna(train.mean())

In [16]:
train

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
5    56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
6    62.0  0.0  4.0     140.0  268.0  0.0      2.0    160.0    0.0      3.6   
7    57.0  0.0  4.0     120.0  354.0  0.0      0.0    163.0    1.0      0.6   
8    63.0  1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
9    53.0  1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
10   57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
11   56.0  0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
12   56.0  1.0  3.0     130.0  256.0  1.0      2.0    142.0    1.0      0.6   
13   44.0  1.0  2.0     120.0  263.0  0.0      0.0    173.0    0.0      0.0   
14   52.0  1.0  3.0     172.0  199.0  1.0      0.0    162.0    0.0      0.5   
15   57.0  1.0  3.0     150.0  168.0  0.0      0.0    174.0    0.0      1.6   
16   48.0  1.0  2.0     110.0  229.0  0.0      0.0    168.0    0.0      1.0   
17   54.0  1.0  4.0     140.0  239.0  0.0      0.0    160.0    0.0      1.2   
18   48.0  0.0  3.0     130.0  275.0  0.0      0.0    139.0    0.0      0.2   
19   49.0  1.0  2.0     130.0  266.0  0.0      0.0    171.0    0.0      0.6   
20   64.0  1.0  1.0     110.0  211.0  0.0      2.0    144.0    1.0      1.8   
21   58.0  0.0  1.0     150.0  283.0  1.0      2.0    162.0    0.0      1.0   
22   58.0  1.0  2.0     120.0  284.0  0.0      2.0    160.0    0.0      1.8   
23   58.0  1.0  3.0     132.0  224.0  0.0      2.0    173.0    0.0      3.2   
24   60.0  1.0  4.0     130.0  206.0  0.0      2.0    132.0    1.0      2.4   
25   50.0  0.0  3.0     120.0  219.0  0.0      0.0    158.0    0.0      1.6   
26   58.0  0.0  3.0     120.0  340.0  0.0      0.0    172.0    0.0      0.0   
27   66.0  0.0  1.0     150.0  226.0  0.0      0.0    114.0    0.0      2.6   
28   43.0  1.0  4.0     150.0  247.0  0.0      0.0    171.0    0.0      1.5   
29   40.0  1.0  4.0     110.0  167.0  0.0      2.0    114.0    1.0      2.0   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
234  54.0  0.0  3.0     160.0  201.0  0.0      0.0    163.0    0.0      0.0   
235  54.0  1.0  4.0     122.0  286.0  0.0      2.0    116.0    1.0      3.2   
236  56.0  1.0  4.0     130.0  283.0  1.0      2.0    103.0    1.0      1.6   
237  46.0  1.0  4.0     120.0  249.0  0.0      2.0    144.0    0.0      0.8   
238  49.0  0.0  2.0     134.0  271.0  0.0      0.0    162.0    0.0      0.0   
239  42.0  1.0  2.0     120.0  295.0  0.0      0.0    162.0    0.0      0.0   
240  41.0  1.0  2.0     110.0  235.0  0.0      0.0    153.0    0.0      0.0   
241  41.0  0.0  2.0     126.0  306.0  0.0      0.0    163.0    0.0      0.0   
242  49.0  0.0  4.0     130.0  269.0  0.0      0.0    163.0    0.0      0.0   
243  61.0  1.0  1.0     134.0  234.0  0.0      0.0    145.0    0.0      2.6   
244  60.0  0.0  3.0     120.0  178.0  1.0      0.0     96.0    0.0      0.0   
245  67.0  1.0  4.0     120.0  237.0  0.0      0.0     71.0    0.0      1.0   
246  58.0  1.0  4.0     100.0  234.0  0.0      0.0    156.0    0.0      0.1   
247  47.0  1.0  4.0     110.0  275.0  0.0      2.0    118.0    1.0      1.0   
248  52.0  1.0  4.0     125.0  212.0  0.0      0.0    168.0    0.0      1.0   
249  62.0  1.0  2.0     128.0  208.0  1.0      2.0    140.0    0.0      0.0   
250  57.0  1.0  4.0     110.0  201.0  0.0      0.0    126.0    1.0      1.5   
251  58.0  1.0  4.0     146.0  218.0  0.0      0.0    105.0    0.0      2.0   
252  64.0  1.0  4.0     128.0  263.0  0.0      0.0    10

In [28]:
for i, val in enumerate(train.num):
    if val != 0:
        train.num[i] = 1 # train.loc[i,'num'] = 1
        #DF.loc['juan','edad'] #escribir
        #DF.iloc[5,3]          #escribir entero

C:\Users\Usuario\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [27]:
train.head(5)

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    1  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

### Definir matrices para entrenar (todas menos col num) y predecir (col num)

In [29]:
X, y = train.iloc[:,:-1], train.iloc[:,-1]

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=38)

In [32]:
display(X_train) #X_train.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
228  54.0  1.0  4.0     110.0  206.0  0.0      2.0    108.0    1.0      0.0   
92   62.0  1.0  3.0     130.0  231.0  0.0      0.0    146.0    0.0      1.8   
162  54.0  0.0  3.0     110.0  214.0  0.0      0.0    158.0    0.0      1.6   
255  42.0  0.0  3.0     120.0  209.0  0.0      0.0    173.0    0.0      0.0   
117  35.0  0.0  4.0     138.0  183.0  0.0      0.0    182.0    0.0      1.4   
29   40.0  1.0  4.0     110.0  167.0  0.0      2.0    114.0    1.0      2.0   
200  50.0  0.0  4.0     110.0  254.0  0.0      2.0    159.0    0.0      0.0   
180  48.0  1.0  4.0     124.0  274.0  0.0      2.0    166.0    0.0      0.5   
97   60.0  0.0  4.0     150.0  258.0  0.0      2.0    157.0    0.0      2.6   
104  49.0  1.0  3.0     120.0  188.0  0.0      0.0    139.0    0.0      2.0   
5    56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
56   50.0  1.0  3.0     140.0  233.0  0.0      0.0    163.0    0.0      0.6   
142  52.0  1.0  2.0     128.0  205.0  1.0      0.0    184.0    0.0      0.0   
164  48.0  1.0  3.0     124.0  255.0  1.0      0.0    175.0    0.0      0.0   
201  64.0  0.0  4.0     180.0  325.0  0.0      0.0    154.0    1.0      0.0   
65   60.0  1.0  4.0     145.0  282.0  0.0      2.0    142.0    1.0      2.8   
148  45.0  1.0  2.0     128.0  308.0  0.0      2.0    170.0    0.0      0.0   
85   44.0  1.0  3.0     140.0  235.0  0.0      2.0    180.0    0.0      0.0   
229  66.0  1.0  4.0     112.0  212.0  0.0      2.0    132.0    1.0      0.1   
179  53.0  1.0  3.0     130.0  246.0  1.0      2.0    173.0    0.0      0.0   
31   60.0  1.0  4.0     117.0  230.0  1.0      0.0    160.0    1.0      1.4   
12   56.0  1.0  3.0     130.0  256.0  1.0      2.0    142.0    1.0      0.6   
35   42.0  1.0  4.0     140.0  226.0  0.0      0.0    178.0    0.0      0.0   
28   43.0  1.0  4.0     150.0  247.0  0.0      0.0    171.0    0.0      1.5   
42   71.0  0.0  2.0     160.0  302.0  0.0      0.0    162.0    0.0      0.4   
260  44.0  0.0  3.0     118.0  242.0  0.0      0.0    149.0    0.0      0.3   
108  61.0  1.0  4.0     120.0  260.0  0.0      0.0    140.0    1.0      3.6   
158  60.0  1.0  4.0     140.0  293.0  0.0      2.0    170.0    0.0      1.2   
22   58.0  1.0  2.0     120.0  284.0  0.0      2.0    160.0    0.0      1.8   
137  62.0  1.0  2.0     120.0  281.0  0.0      2.0    103.0    0.0      1.4   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
57   41.0  1.0  4.0     110.0  172.0  0.0      2.0    158.0    0.0      0.0   
203  64.0  0.0  3.0     140.0  313.0  0.0      0.0    133.0    0.0      0.2   
160  46.0  1.0  2.0     101.0  197.0  1.0      0.0    156.0    0.0      0.0   
259  57.0  1.0  2.0     124.0  261.0  0.0      0.0    141.0    0.0      0.3   
187  66.0  1.0  2.0     160.0  246.0  0.0      0.0    120.0    1.0      0.0   
191  51.0  1.0  4.0     140.0  298.0  0.0      0.0    122.0    1.0      4.2   
129  62.0  0.0  4.0     124.0  209.0  0.0      0.0    163.0    0.0      0.0   
37   57.0  1.0  4.0     150.0  276.0  0.0      2.0    112.0    1.0      0.6   
157  58.0  1.0  4.0     125.0  300.0  0.0      2.0    171.0    0.0      0.0   
235  54.0  1.0  4.0     122.0  286.0  0.0      2.0    116.0    1.0      3.2   
253  51.0  0.0  3.0     120.0  295.0  0.0      2.0    157.0    0.0      0.6   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
52   44.0  1.0  4.0     112.0  290.0  0.0      2.0    153.0    0.0      0.0   
149  60.0  0.0  3.0     102.0  318.0  0.0      0.0    160.0    0.0      0.0   
130  54.0  1.0  3.0     120.0  258.0  0.0      2.0    147.0    0.0      0.4   
151  42.0  0.0  4.0     102.0  265.0  0.0      2.0    122.0    0.0      0.6   
103  71.0  0.0  3.0     110.0  265.0  1.0      2.0    130.0    0.0      0.0   
99   48.0  1.0  4.0     122.0  222.0  0.0      2.0    186.0    0.0      0.0   
116  58.0  1.0  3.0     140.0  211.0  1.0      2.0    16

### Regresión logística

In [33]:
from sklearn.linear_model import LogisticRegression

In [47]:
logistic = LogisticRegression()

In [48]:
y_pred = logistic.fit(X_train, y_train).predict(X_test)

In [49]:
from sklearn.metrics import confusion_matrix


In [50]:
confusion_matrix(y_test, y_pred)

array([[42,  5],
       [ 9, 32]], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(y_test, y_pred)

0.84090909090909094

In [57]:
from sklearn.metrics import precision_recall_curve

In [58]:
precision_recall_curve(y_test, y_pred)

(array([ 0.46590909,  0.72972973,  1.        ]),
 array([ 1.        ,  0.65853659,  0.        ]),
 array([0, 1], dtype=int64))

In [60]:
from sklearn.metrics import log_loss

In [63]:
y_prob = logistic.fit(X_train,y_train).predict_proba(X_test)

In [65]:
log_loss(y_test, y_prob[:,1])

0.37671423276341298

### Probar árboles de classificación

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [68]:
arbol = DecisionTreeClassifier()

In [69]:
y_pred = arbol.fit(X_train, y_train).predict(X_test)

In [70]:
confusion_matrix(y_test, y_pred)

array([[37, 10],
       [12, 29]], dtype=int64)

In [71]:
accuracy_score(y_test, y_pred)

0.75

In [72]:
y_prob = arbol.fit(X_train,y_train).predict_proba(X_test)

In [74]:
y_prob

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,

In [73]:
log_loss(y_test, y_prob[:,1])

8.6347758757375761

### Probar clasificación de Ridge

In [24]:
#sklearn.linear_model import RidgeClassifier