In [1]:
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
train = pd.read_csv('C:\\Users\\Pablo\\MachineLearningTest\\data\\train.csv')

In [3]:
##Cabecera de la base train
train.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    2  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

Cambiar valores de la columna "num"

In [4]:
##Lo que hacemos es reescribir los valores de la columna "num", el 0 por 0 y el 1, 2, 3 por 1
for i in range(len(train.num)):
    if train.num[i]!=0:
        train.loc[i,'num']=1

In [5]:
##Division de la base de datos "train" para probar el modelo
train = train.fillna(0)
X, y = train.iloc[:, :-1], train.iloc[:, -1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
y_pred = log.fit(X_train,y_train).predict(X_test)

In [6]:
##MATRIZ DE CONFUSION DEL MODELO
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[40,  7],
       [10, 31]], dtype=int64)

In [7]:
##RESULTADO DE LA PREDICCION
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.80681818181818177

In [8]:
##Realizamos el uso de componentes principales para intentar mejorar el modelo
from sklearn.decomposition import PCA
pca = PCA(9)
Xtr =pca.fit(X).transform(X)
X_train, X_test, y_train, y_test = train_test_split(Xtr, y, test_size=0.33)
log = LogisticRegression()
y_pred = log.fit(X_train,y_train).predict(X_test)

In [9]:
##Matrix de confusion con nuestro modelo de 9 componentes principales
confusion_matrix(y_test, y_pred)

array([[48,  2],
       [ 5, 33]], dtype=int64)

In [10]:
##Resultado de la prediccion de nuestro modelo de 9 componentes principales
accuracy_score(y_test, y_pred)

0.92045454545454541

In [33]:
##Realizacion del modelo de prediccion con las variables C y K, para poder variar esos valores encontrar con cual obtenemos mejores resultados

from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

def traintest(c, k, pert_split=0.33):
    #result=[]
   
    pca = PCA(k)   
    Xtr =pca.fit(X).transform(X)
        
    X_train, X_test, y_train, y_test = train_test_split(Xtr, y, test_size=0.33, random_state=10)
    result_int=[]
        
        #result_int.append(X_train)
        #result_int.append(y_train)
        #result_int.append(X_test)
        #result_int.append(y_test)
        
    log = LogisticRegression(C=c)
    y_pred = log.fit(X_train,y_train).predict(X_test)
        
        #result_int.append(y_pred)
        
    mat_conf=confusion_matrix(y_test, y_pred)
        
    result_int.append(mat_conf)
        
    scor=accuracy_score(y_test, y_pred)
       
    result_int.append(scor)
        
    #result.append(result_int)
    
    return result_int

In [20]:
res= traintest(0.1, 9)
res[0]

array([[36,  9],
       [12, 31]], dtype=int64)

In [21]:
import itertools
def expandgrid(*itrs):
   product = list(itertools.product(*itrs))
   return {'Var{}'.format(i+1):[x[i] for x in product] for i in range(len(itrs))}

In [22]:
c= np.arange(0.1, 1, 0.05)
k= np.arange(6, 11, 1)
expandgrid(c, k)

parametres = pd.DataFrame.from_dict(expandgrid(c, k))
parametres.columns = ['C','k']

In [23]:
##Creamos una tabla con cada valor de C y K

TP = []
TN = []
FP = []
FN = []
AC = []
for i in range(parametres.shape[0]):
    result = traintest(parametres.loc[i,'C'],parametres.loc[i,'k'])
    confmat = result[0]
    TP.append(confmat[1, 1])
    TN.append(confmat[0, 0])
    FP.append(confmat[0, 1])
    FN.append(confmat[1, 0])
    AC.append(result[1])
parametres["TP"]=TP
parametres["TN"]=TN
parametres["FP"]=FP
parametres["FN"]=FN
parametres["AC"]=AC

In [24]:
parametres

C   k  TP  TN  FP  FN        AC
0   0.10   6  28  35  10  15  0.715909
1   0.10   7  28  36   9  15  0.727273
2   0.10   8  31  37   8  12  0.772727
3   0.10   9  31  36   9  12  0.761364
4   0.10  10  31  37   8  12  0.772727
5   0.15   6  28  35  10  15  0.715909
6   0.15   7  29  36   9  14  0.738636
7   0.15   8  31  37   8  12  0.772727
8   0.15   9  31  37   8  12  0.772727
9   0.15  10  31  37   8  12  0.772727
10  0.20   6  28  35  10  15  0.715909
11  0.20   7  28  36   9  15  0.727273
12  0.20   8  31  37   8  12  0.772727
13  0.20   9  31  37   8  12  0.772727
14  0.20  10  31  37   8  12  0.772727
15  0.25   6  27  35  10  16  0.704545
16  0.25   7  28  36   9  15  0.727273
17  0.25   8  31  37   8  12  0.772727
18  0.25   9  31  37   8  12  0.772727
19  0.25  10  31  37   8  12  0.772727
20  0.30   6  27  35  10  16  0.704545
21  0.30   7  28  36   9  15  0.727273
22  0.30   8  31  37   8  12  0.772727
23  0.30   9  31  37   8  12  0.772727
24  0.30  10  31  37   8  12  0.772727
25  0.35   6  27  35  10  16  0.704545
26  0.35   7  28  36   9  15  0.727273
27  0.35   8  31  37   8  12  0.772727
28  0.35   9  31  37   8  12  0.772727
29  0.35  10  31  37   8  12  0.772727
..   ...  ..  ..  ..  ..  ..       ...
60  0.70   6  26  36   9  17  0.704545
61  0.70   7  29  37   8  14  0.750000
62  0.70   8  30  37   8  13  0.761364
63  0.70   9  31  37   8  12  0.772727
64  0.70  10  31  37   8  12  0.772727
65  0.75   6  26  36   9  17  0.704545
66  0.75   7  29  37   8  14  0.750000
67  0.75   8  30  37   8  13  0.761364
68  0.75   9  31  37   8  12  0.772727
69  0.75  10  31  37   8  12  0.772727
70  0.80   6  26  36   9  17  0.704545
71  0.80   7  29  37   8  14  0.750000
72  0.80   8  30  37   8  13  0.761364
73  0.80   9  31  37   8  12  0.772727
74  0.80  10  31  37   8  12  0.772727
75  0.85   6  26  36   9  17  0.704545
76  0.85   7  29  37   8  14  0.750000
77  0.85   8  30  37   8  13  0.761364
78  0.85   9  31  37   8  12  0.772727
79  0.85  10  31  37   8  12  0.772727
80  0.90   6  26  36   9  17  0.704545
81  0.90   7  29  37   8  14  0.750000
82  0.90   8  30  37   8  13  0.761364
83  0.90   9  31  37   8  12  0.772727
84  0.90  10  31  37   8  12  0.772727
85  0.95   6  26  36   9  17  0.704545
86  0.95   7  29  37   8  14  0.750000
87  0.95   8  30  37   8  13  0.761364
88  0.95   9  31  37   8  12  0.772727
89  0.95  10  31  37   8  12  0.772727

[90 rows x 7 columns]

In [30]:
parametres[parametres.AC>0.771]

C   k  TP  TN  FP  FN        AC
2   0.10   8  31  37   8  12  0.772727
4   0.10  10  31  37   8  12  0.772727
7   0.15   8  31  37   8  12  0.772727
8   0.15   9  31  37   8  12  0.772727
9   0.15  10  31  37   8  12  0.772727
12  0.20   8  31  37   8  12  0.772727
13  0.20   9  31  37   8  12  0.772727
14  0.20  10  31  37   8  12  0.772727
17  0.25   8  31  37   8  12  0.772727
18  0.25   9  31  37   8  12  0.772727
19  0.25  10  31  37   8  12  0.772727
22  0.30   8  31  37   8  12  0.772727
23  0.30   9  31  37   8  12  0.772727
24  0.30  10  31  37   8  12  0.772727
27  0.35   8  31  37   8  12  0.772727
28  0.35   9  31  37   8  12  0.772727
29  0.35  10  31  37   8  12  0.772727
32  0.40   8  31  37   8  12  0.772727
33  0.40   9  31  37   8  12  0.772727
34  0.40  10  31  37   8  12  0.772727
37  0.45   8  31  37   8  12  0.772727
38  0.45   9  31  37   8  12  0.772727
39  0.45  10  31  37   8  12  0.772727
42  0.50   8  31  37   8  12  0.772727
43  0.50   9  31  37   8  12  0.772727
44  0.50  10  31  37   8  12  0.772727
47  0.55   8  31  37   8  12  0.772727
48  0.55   9  31  37   8  12  0.772727
49  0.55  10  31  37   8  12  0.772727
52  0.60   8  31  37   8  12  0.772727
53  0.60   9  31  37   8  12  0.772727
54  0.60  10  31  37   8  12  0.772727
57  0.65   8  31  37   8  12  0.772727
58  0.65   9  31  37   8  12  0.772727
59  0.65  10  31  37   8  12  0.772727
63  0.70   9  31  37   8  12  0.772727
64  0.70  10  31  37   8  12  0.772727
68  0.75   9  31  37   8  12  0.772727
69  0.75  10  31  37   8  12  0.772727
73  0.80   9  31  37   8  12  0.772727
74  0.80  10  31  37   8  12  0.772727
78  0.85   9  31  37   8  12  0.772727
79  0.85  10  31  37   8  12  0.772727
83  0.90   9  31  37   8  12  0.772727
84  0.90  10  31  37   8  12  0.772727
88  0.95   9  31  37   8  12  0.772727
89  0.95  10  31  37   8  12  0.772727

In [80]:
test = pd.read_csv('C:\\Users\\Pablo\\MachineLearningTest\\data\\test.csv')

In [81]:
test.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1  42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
2  52.0  1.0  4.0     128.0  204.0  1.0      0.0    156.0    1.0      1.0   
3  59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4  40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   

   slope   ca thal  
0    2.0  1.0  3.0  
1    2.0  0.0  6.0  
2    2.0  0.0    ?  
3    2.0  1.0  6.0  
4    1.0  0.0  7.0

In [74]:
[i for i, el in enumerate(test.thal) if el=="?"]

[2]

In [82]:
a = []
for i, el in enumerate(test.ca):
    if el=="?":
        a.append(np.nan)
    else:
        a.append(float(el))
test.ca = a

In [83]:
b = []
for i, el in enumerate(test.thal):
    if el=="?":
        b.append(np.nan)
    else:
        b.append(float(el))
test.thal = b

In [84]:
test = test.fillna(test.mean())

In [85]:
test.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1  42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
2  52.0  1.0  4.0     128.0  204.0  1.0      0.0    156.0    1.0      1.0   
3  59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4  40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   

   slope   ca      thal  
0    2.0  1.0  3.000000  
1    2.0  0.0  6.000000  
2    2.0  0.0  5.131579  
3    2.0  1.0  6.000000  
4    1.0  0.0  7.000000

In [92]:
pca = PCA(8)   
Xtr=pca.fit(train).transform(train)
Xt=pca.fit(test).transform(test)
log = LogisticRegression()
y_pred = log.fit(Xtr,np.array(train.num)).predict(Xt)

In [93]:
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [94]:
test['num'] = list(y_pred)

In [95]:
test.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1  42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
2  52.0  1.0  4.0     128.0  204.0  1.0      0.0    156.0    1.0      1.0   
3  59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4  40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   

   slope   ca      thal  num  
0    2.0  1.0  3.000000    1  
1    2.0  0.0  6.000000    1  
2    2.0  0.0  5.131579    1  
3    2.0  1.0  6.000000    0  
4    1.0  0.0  7.000000    1

In [96]:
y_prob = log.fit(Xtr,np.array(train.num)).predict_proba(Xt)

In [101]:
test["prob"] = y_prob[:,1]

In [102]:
test

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1   42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
2   52.0  1.0  4.0     128.0  204.0  1.0      0.0    156.0    1.0      1.0   
3   59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4   40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   
5   42.0  1.0  3.0     130.0  180.0  0.0      0.0    150.0    0.0      0.0   
6   61.0  1.0  4.0     140.0  207.0  0.0      2.0    138.0    1.0      1.9   
7   66.0  1.0  4.0     160.0  228.0  0.0      2.0    138.0    0.0      2.3   
8   46.0  1.0  4.0     140.0  311.0  0.0      0.0    120.0    1.0      1.8   
9   71.0  0.0  4.0     112.0  149.0  0.0      0.0    125.0    0.0      1.6   
10  59.0  1.0  1.0     134.0  204.0  0.0      0.0    162.0    0.0      0.8   
11  64.0  1.0  1.0     170.0  227.0  0.0      2.0    155.0    0.0      0.6   
12  66.0  0.0  3.0     146.0  278.0  0.0      2.0    152.0    0.0      0.0   
13  39.0  0.0  3.0     138.0  220.0  0.0      0.0    152.0    0.0      0.0   
14  57.0  1.0  2.0     154.0  232.0  0.0      2.0    164.0    0.0      0.0   
15  58.0  0.0  4.0     130.0  197.0  0.0      0.0    131.0    0.0      0.6   
16  57.0  1.0  4.0     110.0  335.0  0.0      0.0    143.0    1.0      3.0   
17  47.0  1.0  3.0     130.0  253.0  0.0      0.0    179.0    0.0      0.0   
18  55.0  0.0  4.0     128.0  205.0  0.0      1.0    130.0    1.0      2.0   
19  35.0  1.0  2.0     122.0  192.0  0.0      0.0    174.0    0.0      0.0   
20  61.0  1.0  4.0     148.0  203.0  0.0      0.0    161.0    0.0      0.0   
21  58.0  1.0  4.0     114.0  318.0  0.0      1.0    140.0    0.0      4.4   
22  58.0  0.0  4.0     170.0  225.0  1.0      2.0    146.0    1.0      2.8   
23  58.0  1.0  2.0     125.0  220.0  0.0      0.0    144.0    0.0      0.4   
24  56.0  1.0  2.0     130.0  221.0  0.0      2.0    163.0    0.0      0.0   
25  56.0  1.0  2.0     120.0  240.0  0.0      0.0    169.0    0.0      0.0   
26  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
27  55.0  0.0  2.0     132.0  342.0  0.0      0.0    166.0    0.0      1.2   
28  44.0  1.0  4.0     120.0  169.0  0.0      0.0    144.0    1.0      2.8   
29  63.0  1.0  4.0     140.0  187.0  0.0      2.0    144.0    1.0      4.0   
30  63.0  0.0  4.0     124.0  197.0  0.0      0.0    136.0    1.0      0.0   
31  41.0  1.0  2.0     120.0  157.0  0.0      0.0    182.0    0.0      0.0   
32  59.0  1.0  4.0     164.0  176.0  1.0      2.0     90.0    0.0      1.0   
33  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0      0.2   
34  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
35  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
36  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
37  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   
38  38.0  1.0  3.0     138.0  175.0  0.0      0.0    173.0    0.0      0.0   

    slope        ca      thal  num      prob  
0     2.0  1.000000  3.000000    1  0.908707  
1     2.0  0.000000  6.000000    1  0.922905  
2     2.0  0.000000  5.131579    1  0.568856  
3     2.0  1.000000  6.000000    0  0.468730  
4     1.0  0.000000  7.000000    1  0.676916  
5     1.0  0.000000  3.000000    0  0.040517  
6     1.0  1.000000  7.000000    1  0.941707  
7     1.0  0.000000  6.000000    1  0.947020  
8     2.0  2.000000  7.000000    1  0.918958  
9     2.0  0.000000  3.000000    0  0.139371  
10    1.0  2.000000  3.000000    0  0.007749  
11    2.0  0.000000  7.000000    0  0.240606  
12    2.0  1.000000  3.000000    0  0.166133  
13    2.0  0.000000  3.000000    0  0.075522  
14    1.0  1.000000  3.000000    0  0.063211  
15    2.0  0.000000  3.000000    0  0.142138  
16    2.0  1.000000  7.000000    1  0.971332  
17    1.0  0.000000  3.000000    0  0.

In [105]:
test.to_csv('C:\\Users\\Pablo\\MachineLearningTest\\data\\resultsPablo.csv', index=False)